# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'

target 'StarKids1' do

use_frameworks!


pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
end